### ISSUE TITLE
Switch onClick listener to when statements

### ISSUE THREAD

**Issue by Bkirchhoff03** [NickWebber21/CSE5236Proj#14]

**Comment by NickWebber21** [comment]
buttons now work: 
the issue was that we were using fragment layout as the activity layout
LoginActivity was using the same layout as LoginFragment and this wasn't setup to manage the fragment properly
the layout for LoginActivity needed a specific container to hold the fragment which is what i added

**Comment by NickWebber21** [comment]
![image](https://github.com/user-attachments/assets/3f8ae96c-97db-48ed-a3c4-84ce78d57615)
